#!/bin/bash
source /etc/restic.conf
#Abandon the process on first failure
set -e 
export $(awk -F= '/^(RESTIC|AWS|ST|OS|B2|AZURE|GOOGLE|RCLONE)_[A-Z_]*=/{print $1}'</etc/restic.conf|grep -E -v '(_PASSWORD|^ST_KEY)$')
#Make the backup
function restic ()
{
	eval 'ionice -c Idle /usr/bin/restic' "$@"
}
function defaultfs ()
{
        findmnt -l -n -t nosquashfs --real -o TARGET,SOURCE|awk '/[^]]$/{print $1}'
}

function purge ()
{
    restic forget -q --prune --keep-within "${WITHIN:-48h}" -d "${DAILY:-7}" -w "${WEEKLY:-4}" -m "${MONTHLY:-12}" -y "${YEARLY:-100}"
}

function dobackups ()
{
    until restic snapshots -H "$(hostname -s)"|awk '{print $5}'|grep "${1}" >/dev/null
    do
	restic backup --tag="${1}" -q -x ${FILESYSTEMS:-$(defaultfs)} 
	sleep 300
    done
    restic cache -q --cleanup
}

case "$1" in
    "")
	dobackups "$(date +%F)";;
    
    CLEANUP)
	purge;;
    
    LIST)
	restic snapshots |grep '^[a-z0-9]';;
    *)
	restic "$@";;
esac
